package-lock.json
scripts/start-server.js
src/components/AlgoOrderTable/AlgoOrderTable.columns.js
src/components/AlgoOrderTable/AlgoOrderTable.js
src/components/HFUI/HFUI.js
src/main.scss
src/pages/AlgoOrders/AlgoOrders.js
src/ui/SideNavBar/_SideNavBar.scss
src/ui/Table/Table.props.js
src/ui/Table/_Table.scss
src/ui/Table/index.js

- update package lock to fixed commits
- general scss changes
- redirect '/' to '/algo-orders'
- remove non-mvp data from algo orders table

Mvp preperation

---

src/components/NotificationsSidebar/Notification.js
src/components/OrderForm/FieldComponents/input.range.js
src/components/OrderForm/OrderForm.container.js
src/components/OrderForm/OrderForm.helpers.js
src/components/OrderForm/OrderForm.js
src/components/OrderForm/style.scss
src/orders/bitfinex/fok.js
src/orders/bitfinex/ioc.js
src/orders/bitfinex/limit.js
src/orders/bitfinex/market.js
src/orders/bitfinex/stop.js
src/orders/bitfinex/stop_limit.js
src/orders/bitfinex/trailing_stop.js
src/pages/Trading/style.scss
src/ui/Input/Input.js
src/ui/Panel/index.js

Needs:
* https://github.com/bitfinexcom/bfx-hf-server/pull/11
* https://github.com/bitfinexcom/bfx-hf-algo/pull/22

Feature: Support futures for both atomic and algo orders

---

src/components/OrderForm/OrderForm.js
src/components/OrderForm/OrderFormModal.js

(fix) typo and duplicate API key submit modal in OF

---

src/components/OrderBook/OrderBook.js
src/components/OrderForm/FieldComponents/input.date.js
src/components/OrderForm/FieldComponents/input.dropdown.js
src/components/OrderForm/FieldComponents/input.dropdown.props.js
src/components/OrderForm/FieldComponents/input.number.js
src/components/OrderForm/FieldComponents/input.radio.js
src/components/OrderForm/OrderForm.helpers.js
src/components/OrderForm/OrderForm.js
src/components/TradingStatePanel/TradingStatePanel.js
src/pages/Settings/Settings.js
src/pages/Settings/Settings.props.js
src/pages/StrategyEditor/StrategyEditor.js
src/ui/Checkbox/Checkbox.js
src/ui/Input/Input.js
src/ui/Input/Input.props.js
src/ui/Panel/index.js
src/ui/PanelSettings/PanelSettings.props.js
src/ui/RadioButton/RadioButton.props.js
src/ui/RadioButton/index.js

fixed unique keys error, and all other console erros

fix react errors

---

src/components/Chart/Chart.js
src/pages/Settings/Settings.container.js
src/pages/Settings/Settings.js
src/pages/Settings/Settings.props.js

Removed chart selection
Removed theme from code 
Updated settings page
Fixed Checkbox errors
With this PR need to merge next: 
https://github.com/bitfinexcom/bfx-hf-models/pull/16
https://github.com/bitfinexcom/bfx-hf-server/pull/41

remove chart

---

src/redux/reducers/ws/trades.js

remove old orders if currentOrders.length > 25 to fit new orders in currentOrders array

fix trades table

---

src/components/AlgoOrdersTable/AlgoOrdersTable.container.js
src/components/AlgoOrdersTable/AlgoOrdersTable.js
src/components/AlgoOrdersTable/AlgoOrdersTable.props.js
src/components/AlgoOrdersTablePanel/AlgoOrdersTablePanel.container.js
src/components/AlgoOrdersTablePanel/AlgoOrdersTablePanel.js
src/components/AlgoOrdersTablePanel/index.js
src/components/AtomicOrdersTable/AtomicOrdersTable.container.js
src/components/AtomicOrdersTable/AtomicOrdersTable.js
src/components/AtomicOrdersTable/AtomicOrdersTable.props.js
src/components/AtomicOrdersTablePanel/AtomicOrdersTablePanel.container.js
src/components/AtomicOrdersTablePanel/AtomicOrdersTablePanel.js
src/components/BalancesTable/BalancesTable.container.js
src/components/BalancesTable/BalancesTable.js
src/components/BalancesTable/BalancesTable.props.js
src/components/BalancesTablePanel/BalancesTablePanel.container.js
src/components/BalancesTablePanel/BalancesTablePanel.js
src/components/GridLayout/GridLayout.helpers.js
src/components/PositionsTable/PositionsTable.container.js
src/components/PositionsTable/PositionsTable.js
src/components/PositionsTable/PositionsTable.props.js
src/components/PositionsTablePanel/PositionsTablePanel.container.js
src/components/PositionsTablePanel/PositionsTablePanel.js
src/components/TradingStatePanel/TradingStatePanel.container.js
src/components/TradingStatePanel/TradingStatePanel.js
src/redux/actions/ui.js

fixed issues:  
- algoOrders table 
- atomicOrders table
- balances table
- positions table

make all tables independent

---

src/components/ExchangeInfoBar/style.scss
src/pages/Settings/Settings.js
src/ui/Button/style.scss
src/ui/Checkbox/Checkbox.js
src/ui/Input/style.scss
src/ui/Panel/style.scss

fixed issues: 
- general info not visible on 1370 px width break line
- UI: Trading Stage X and drag not visible because of width

fix css bugs

---

src/pages/Authentication/style.scss

inputs were not round  on the auth page

fix css for auth inputs

---

src/components/ExchangeInfoBar/ExchangeInfoBar.helpers.js
src/components/OrderHistoryTable/OrderHistoryTable.columns.js
src/components/OrderHistoryTable/OrderHistoryTable.helpers.js

added avg price
added pair column
reworked status format

improve order history table

---

src/components/Backtester/forms/HistoricalForm.js
src/components/OrderForm/FieldComponents/input.date.js
src/components/OrderForm/FieldComponents/input.date.props.js

- Fixed future dates selecting in backtesting
- Full description https://app.asana.com/0/1125859137800433/1199182620003271

Fix future dates selecting in backtesting

---

src/components/Backtester/forms/HistoricalForm.js
src/components/Backtester/style.scss

Added market filtering ability instead of searching with scrolling

add market filtering ability

---

src/components/OrderHistoryTable/OrderHistoryTable.helpers.js

fixed issue when history table crashed because in some cases statuses were processed incorrectly

Better status processing

---

package-lock.json
package.json
src/components/OrderForm/FieldComponents/input.date.js
src/components/OrderForm/FieldComponents/input.date.props.js
src/index.scss

- Fixed month selection issues in backtesting
- Full description https://app.asana.com/0/1125859137800433/1199182620003267

Fix month selector in backtesting

---

package.json

add bufferutil

---

src/components/FavoriteTradingPairs/FavoriteTradingPairs.props.js
src/components/FavoriteTradingPairs/index.js

fixed keys warning and props warning

fix warnings

---

src/components/PositionsTablePanel/PositionsTablePanel.js

use bitfinex as default exchange

fix positions cancel

---

README.md
package-lock.json
package.json

When user tries to run the server on ubuntu, they run into the issue "Error: spawn concurrently ENOENT" because of the missing package concurrently.
Also, in order to store local db, the user is misguided to create .hfdb instead of .honeyframework because the readme isn't updated.
Here's a fix to both of the issues that the new users frequently run into.

ubuntu installation fail issue fix

---

src/components/PositionsTable/PositionsTable.container.js
src/components/PositionsTable/PositionsTable.js

Render positions without opened TradingStatePanel

Positions table live updates

---

src/pages/Trading/style.scss

- Fixed execute order window height
- Full description https://app.asana.com/0/1125859137800433/1199634604010522

Fix execute order window height

---

src/components/OrderBook/OBSide.js
src/components/OrderBook/OrderBook.js

- Fixed order book negative amounts in `Stacked View` mode and when `Sum Amounts` disabled
- Full description https://app.asana.com/0/1125859137800433/1199667429846914

Fix negative amounts in the order book

---

src/components/ExchangeInfoBar/ExchangeInfoBar.container.js
src/components/ExchangeInfoBar/style.scss
src/components/MarketSelect/style.scss
src/components/OrderForm/OrderForm.container.js
src/components/OrderForm/OrderForm.js
src/components/TradingModeModal/TradingModeModal.js
src/pages/Settings/Settings.container.js
src/pages/Settings/Settings.js
src/pages/Settings/style.scss
src/redux/index.js
src/redux/sagas/ws/on_add_channel_req.js
src/redux/selectors/ui/get_current_mode.js

use space-between instead of the gap,
use hash History instead of the Browser History,
made the market dropdown wider,
made the app to provide the mode, when entering API creds in the order block.

fix styles; mode issues; window reload; ticker

---

src/components/ActiveAlgoOrdersModal/ActiveAlgoOrdersModal.js
src/pages/Trading/Trading.container.js
src/pages/Trading/Trading.js
src/redux/sagas/ao/handle_active_algo_orders.js

- Added cancel all orders functionality and updated related handlers and sagas
- Full description https://app.asana.com/0/1125859137800433/1200011814493483

Add cancel all orders & update popup behavior

---

src/pages/Settings/Settings.container.js
src/pages/Settings/Settings.js
src/pages/Trading/Trading.container.js
src/pages/Trading/Trading.js
src/redux/middleware/ws/on_message.js
src/redux/reducers/ao/index.js

- Updated popup handlers to not refetch active AOs on page switch
- Full description https://app.asana.com/0/1125859137800433/1200011246524975

Update popup handlers to not refetch active AOs on page switch

---

src/components/TradingModeModal/TradingModeModal.container.js
src/components/TradingModeModal/TradingModeModal.js

- Updated trading mode modal description and `changeTradingMode` handler

Update trading mode modal description and changeTradingMode handler

---

src/components/OrderForm/OrderForm.helpers.js

The existing code doesn't test for the greater than condition when the provided value is 0. This fix checks for the greater than condition when the value is 0 as well.

check for greater than condition if provided even when 0

---

.gitignore
src/components/TradingStatePanel/TradingStatePanel.js

ASANA Ticket: [UI: No balance if only trading stage component](https://app.asana.com/0/1125859137800433/1200110374561636/f)
Before:
https://www.loom.com/share/faabb1fdf6bd48bab11c44b4e786965f
After:

Fix for empty balances Trading stage bug

---

src/components/BalancesTable/BalancesTable.columns.js

ASANA Ticket: [UI: remove exchange table in balances](https://app.asana.com/0/1125859137800433/1199640043344218/f)
UI Demo:

Removed 'Exchange' column from balances table

---

src/components/AtomicOrdersTable/AtomicOrdersTable.columns.js

ASANA Ticket: [UI: Action column with X should not be sortable](https://app.asana.com/0/1125859137800433/1199640043344222/f)
UI Demo:

Made 'Actions' non-sortable

---

src/components/NotificationsSidebar/NotificationsSidebar.js
src/redux/middleware/ws/index.js
src/redux/sagas/ws/on_flush_data_from_exchange.js

This PR fixes the start-up application freeze bug (due to app wasn't able to connect to the WebSocket API server in time) and 'Encountered two children with the same key' NotificationsSidebar error. 
Before:
After:

fix: start-up application freeze

---

src/components/NotificationsSidebar/Notification.js

Issue: https://www.loom.com/share/4c1baa55a2014ac892469657ca31d449
Description: Fix app crash on strategy editor with following steps:
- run backtest
- switch to Market data
- click start to run backtest again
https://user-images.githubusercontent.com/29878604/113999278-854edb80-9877-11eb-90bb-605296ec07ba.mov

(fix) strategy/backtest: fix app crash

---

src/pages/Settings/style.scss

(fix) Settings Page: hidden save button

---

src/orders/bitfinex/fok.js
src/orders/bitfinex/ioc.js
src/orders/bitfinex/limit.js
src/orders/bitfinex/market.js
src/orders/bitfinex/stop.js
src/orders/bitfinex/stop_limit.js
src/orders/bitfinex/trailing_stop.js

ASANA Ticket: [Reverse order of buy and sell buttons](https://app.asana.com/0/1125859137800433/1200136010718932/f)

Reversed buy/sell buttons

---

src/index.scss

ASANA Ticket: [Settings eye icon (show passwords) outside of input](https://app.asana.com/0/1125859137800433/1200206336011007/f)
**UI Demonstration**
Before:
After:

fix: broken app layout

---

src/components/OrderBook/OrderBook.helpers.js
src/components/OrderBook/OrderBook.js
src/components/OrderBookPanel/OrderBookPanel.container.js
src/components/OrderBookPanel/OrderBookPanel.js
src/redux/reducers/ui/index.js
src/redux/selectors/ui/get_market_books.js
src/redux/selectors/ui/index.js

Description:
fix: trading terminal book not in sync with selected market
fix: for market data, when more than one book widgets are subscribed to same market, if change market for one, others are unsubscribed
After fix:
https://user-images.githubusercontent.com/29878604/115546883-310a1980-a2c3-11eb-8252-fddddaa19a91.mov

(fix) book sub/unsub issues 

---

src/components/Backtester/Backtester.js
src/components/Backtester/Results/style.scss
src/components/Backtester/forms/HistoricalForm.js
src/components/Backtester/reports/HistoricalReport.js
src/components/Backtester/style.scss
src/pages/StrategyEditor/StrategyEditor.js

ASANA Ticket: [Backtester Volatility number cut on display](https://app.asana.com/0/1125859137800433/1200200406857160/f)

fix: backtest chart

---

src/components/OrderBook/OrderBook.helpers.js
src/components/OrderBook/OrderBook.js

Task: [UI: Order book cog >Stacked View check only should not contain Total](https://app.asana.com/0/1125859137800433/1199640043344214/f)
Now:
https://user-images.githubusercontent.com/29878604/115506733-d78cf500-a298-11eb-89fa-a81bbe296e2d.mov

(improvement) book: keep cols consistent for stacked/non-stacked view

---

src/components/ActiveAlgoOrdersModal/ActiveAlgoOrdersModal.table.js
src/components/ActiveAlgoOrdersModal/style.scss
src/components/GridLayoutPage/GridLayoutPage.js

ASANA Ticket: [UI: Algo Popup: make whole row clickable](https://app.asana.com/0/1125859137800433/1200221691555199/f)
Before:
After:

fix: algo orders modal

---

src/index.js

- [ufx Trades should show local time, not UTC](https://app.asana.com/0/0/1200125269390660/1200263952747161/f)
-  Updated `UfxStoreProvider` config to provide local time in ufx `Trades`

Update UfxStoreProvider to provide local time

---

src/components/OrderForm/OrderForm.helpers.js
src/components/OrderForm/OrderForm.js

ASANA Ticket: [UI: Feature: AMPF0 max leverage should be x20](https://app.asana.com/0/1125859137800433/1198951310260685/f)

added helper for resetting default & max leverage value

---

src/pages/Settings/Settings.js

ASANA Ticket: [Not possible to type API in settings](https://app.asana.com/0/1125859137800433/1200272741470135/f)
https://user-images.githubusercontent.com/35810911/116860536-3afc1880-abf1-11eb-8a31-e29eef3bd8ef.mp4

fix: freezed API inputs bug

---

src/components/ExchangeInfoBar/ExchangeInfoBar.Button.js
src/components/ExchangeInfoBar/ExchangeInfoBar.js
src/components/OrderForm/OrderForm.js
src/components/TradingStatePanel/TradingStatePanel.js
src/ui/Panel/index.js

- [UI: fix lint issues](https://app.asana.com/0/1125859137800433/1200316084535950/f)
- Added missed prop-types/default props and cleaned unused code in several components
- Fixed compilation warnings:

Refactor: add missed prop-types, unused code cleanup

---

src/redux/reducers/ws/positions.js

ASANA Ticket: [Positions issue](https://app.asana.com/0/1125859137800433/1200327885160052/f)
https://user-images.githubusercontent.com/35810911/118492608-b5f42180-b70f-11eb-8044-40ecf5a0f443.mp4

fix: positions duplicating issue

---

src/components/OrderForm/style.scss

ASANA Ticket: [No API, execute orders have algo and few pixels of selected order](https://app.asana.com/0/1125859137800433/1200331980909837/f)

fix: overlapping order form modal

---

src/pages/Authentication/style.scss
src/pages/Settings/style.scss
src/ui/Input/style.scss

- Fixed icon alignment in several inputs
- Task: [UI: fix icons alignment](https://app.asana.com/0/1125859137800433/1200332623388391)

Fix: icons alignment

---

.gitignore
package.json

Using the already existing log folder to log algo data for dev mode.

log algo data for dev mode

---

src/components/AtomicOrdersTablePanel/AtomicOrdersTablePanel.js
src/components/PositionsTable/PositionsTable.columns.js
src/components/PositionsTable/PositionsTable.container.js
src/components/PositionsTable/PositionsTable.js
src/index.scss

[Postions: integrate ufx TableVirtual comp](https://app.asana.com/0/1125859137800433/1200372030659900/f)
Change Description:
- use ufx VirtualTable component
- refactor to fn component
- remove redundant filtered positions logic that is already done in TradingStatePanel comp
- fix active market filter not working for positions
UI:

(refactor) positions table component

---

src/components/ExchangeInfoBar/ExchangeInfoBar.js
src/components/ExchangeInfoBar/style.scss

ASANA Ticket: [Prevent overlapping of header on smaller screens](https://app.asana.com/0/1125859137800433/1200334285096204/f)

fix: header overlap

---

src/components/PositionsTable/PositionsTable.columns.js
src/redux/reducers/ws/positions.js

ASANA Ticket: [Positions of same ticker are appending, not summing up](https://app.asana.com/0/1125859137800433/1200352277069546/f)

Fixed positions filtering & using lodash helpers

---

src/components/Backtester/Results/ResultHeader.js
src/components/Backtester/Results/ResultHeader.props.js
src/components/Backtester/Results/ResultRow.js
src/components/Backtester/Results/ResultRow.props.js
src/components/Backtester/Results/Results.js
src/components/Backtester/Results/Results.props.js

- Removed .props file
- Replaced and fixed prop types and default props
- Switched component to memoized functional component

fixed: Results components props and refactoring

---

src/components/FavoriteTradingPairs/index.js
src/components/FavoriteTradingPairs/style.scss

(Improvement) Improve how favorites' breaks lines

---

src/pages/MarketData/MarketData.container.js
src/pages/MarketData/MarketData.js
src/pages/MarketData/MarketData.props.js

ticket - https://app.asana.com/0/1125859137800433/1199672861422564
- Switched to functional component
- Fixed prop types
- Removed unused selectors and dispatch methods

fix: MarketData: refactoring

---

src/pages/Authentication/Authentication.js
src/pages/Authentication/Authentication.props.js
src/pages/Authentication/AuthenticationConnectingForm.js
src/pages/Authentication/AuthenticationInitForm.js
src/pages/Authentication/AuthenticationInitForm.props.js
src/pages/Authentication/AuthenticationUnlockForm.js

FIXED - https://github.com/bitfinexcom/bfx-hf-ui/pull/422

fix: Auth components: fixed props and refactoring (instead of 422)

---

src/components/StrategyEditor/StrategyEditor.js
src/components/StrategyEditor/style.scss
src/index.scss

[ticket](https://app.asana.com/0/1125859137800433/1200383864759504)
fixed font-size

StrategyEditor: fixed styles

---

src/components/AlgoOrdersTable/AlgoOrdersTable.columns.js

ASANA Ticket: [Algo Orders integration](https://app.asana.com/0/1125859137800433/1200183047626381/f)

fix: created column width in algo orders table

---

src/components/PositionsTable/PositionsTable.container.js
src/components/PositionsTable/PositionsTable.js
src/components/TradingStatePanel/TradingStatePanel.js

Task: [Position table is not independent from Trading State panel](https://app.asana.com/0/1125859137800433/1200383864348728/f)

(fix) Position table is not independent from Trading State panel

---

src/components/StrategyEditor/StrategyEditorPanel/StrategyEditorPanel.js
src/components/StrategyEditor/style.scss

[task](https://app.asana.com/0/1125859137800433/1199589158804343)
- showing title of strategy or message "unsaved strategy" if user unsaved one

Strategy Editor: Show Title of Currently Loaded Strategy

---

src/components/AlgoOrdersTablePanel/AlgoOrdersTablePanel.js
src/components/AtomicOrdersTable/AtomicOrdersTable.js
src/components/AtomicOrdersTablePanel/AtomicOrdersTablePanel.js
src/components/BalancesTablePanel/BalancesTablePanel.js
src/components/PositionsTablePanel/PositionsTablePanel.js
src/pages/Authentication/style.scss

ticket - https://app.asana.com/0/1125859137800433/1200392056505585/f
Fixed components: 
- PositionsTablePanel
- AlgoOrdersTablePanel
- AtomicOrdersTablePanel

fix: same dark background color in all table pannels + fixed proptypes

---

src/components/OrderForm/FieldComponents/input.date.js
src/components/OrderForm/FieldComponents/input.percent.js

Description:
- improved validation for percent values
- fixed input date issue
UI Demo:

fix: Orderform inputs

---

src/components/RemoveExistingStrategyModal/RemoveExistingStrategyModal.js
src/components/RemoveExistingStrategyModal/index.js
src/components/StrategyEditor/StrategyEditor.js
src/components/StrategyEditor/StrategyEditorPanel/StrategyEditorPanel.js
src/ui/Modal/style.scss

issues: 
https://bitfinex.slack.com/archives/CKKLH6HA9/p1622533738154600
https://bitfinex.slack.com/archives/CKKLH6HA9/p1622534511155800
- Separated RemoveExistingStrategyModal from StrategyEditorPanel to component
- Fixed issue with input and submit button in RemoveExistingStrategyModal
- Fixed style of error message

fix: StrategyEditor

---

src/pages/Authentication/AuthenticationUnlockForm.js

ASANA Ticket: [auth page reloading when pressing 'Enter'](https://app.asana.com/0/1125859137800433/1200395526204675/f)
UI Before:
https://user-images.githubusercontent.com/35810911/119960896-fa47b300-bf94-11eb-9241-c94801e6e110.mp4
UI After:
https://user-images.githubusercontent.com/35810911/119960913-003d9400-bf95-11eb-8e82-a731f2274b0b.mp4

fix: auth page reloading bug

---

src/components/Backtester/forms/HistoricalForm.js
src/components/CreateNewLayoutModal/CreateNewLayoutModal.js
src/components/CreateNewLayoutModal/CreateNewLayoutModal.props.js
src/components/RefillBalanceModal/RefillBalanceModal.js

tasks: 
- https://app.asana.com/0/1125859137800433/1200386412895370/f
- https://app.asana.com/0/1125859137800433/1199672861422564/f
HistoricalForm: fixed props 
CreateNewLayoutModal: switched to fn component and fixed prop types
RefillBalanceModal: resolving problem with props validation

fix: refactoring & fixing proptypes

---

src/pages/Settings/APIKeysSection.js
src/pages/Settings/CheckboxesSections.js
src/pages/Settings/DeadMenSwitch.js
src/pages/Settings/Settings.js
src/pages/Settings/style.scss

[ticket](https://app.asana.com/0/1125859137800433/1199504432728173)
- Settings: switched to fn component && was broken into components
- Added "Update keys" button for saving only api keys
- "Save" button saves only settings without keys

feature: added "Update API Keys " button

---

src/components/AtomicOrdersTable/AtomicOrdersTable.columns.js
src/components/AtomicOrdersTable/style.scss

ASANA Ticket: [Atomic Orders improvement](https://app.asana.com/0/1125859137800433/1200383864348736/f)
UI Demo:

improvement: atomic orders table

---

src/components/BalancesTable/BalancesTable.columns.js
src/components/PositionsTable/PositionsTable.columns.js
src/index.scss
src/util/ui.js

ASANA Ticket: [BALANCES-component does not match with Web](https://app.asana.com/0/1125859137800433/1200403923487580/f)
UI Demo:

improvement: made tables to match the web version

---

src/components/ExchangeInfoBar/ExchangeInfoBar.container.js
src/components/ExchangeInfoBar/ExchangeInfoBar.js
src/components/ExchangeInfoBar/style.scss
src/components/Layout/Layout.js
src/components/Navbar/style.scss
src/components/OrderForm/OrderForm.js
src/pages/Trading/Trading.container.js
src/pages/Trading/Trading.js
src/pages/Trading/style.scss
src/redux/actions/ws.js
src/redux/middleware/ws/on_message.js
src/redux/sagas/ws/on_pub_subscribed.js
src/redux/selectors/meta/get_market_by_symbol.js
src/redux/selectors/meta/index.js
src/redux/selectors/ws/get_favorite_pairs.js
src/redux/selectors/ws/get_favorite_pairs_object.js
src/redux/selectors/ws/get_tickers_array.js
src/redux/selectors/ws/index.js

[ticket](https://app.asana.com/0/1125859137800433/1199600122306030/f)

[WIP] feature: Ticker and TickerList components

---

src/components/TradingStatePanel/TradingStatePanel.container.js
src/components/TradingStatePanel/TradingStatePanel.js

ASANA Ticket: [TRADING STATE-Only able to filter with the recent symbol](https://app.asana.com/0/1125859137800433/1200413686032249/f)
Description:
- added ability to filter trading state tables with any market pair.
- optimised & refactored the component in clear, functional way.
https://user-images.githubusercontent.com/35810911/120623196-0cbb6400-c44f-11eb-8225-2ef974dba3a9.mp4

improvement: trading state

---

src/pages/Settings/Settings.js

ticket - https://app.asana.com/0/1125859137800433/1199504432728173/f
Fixed fn argument

fix: Bug with setting paper api key

---

src/components/NavbarButton/NavbarButton.js

ticket - https://app.asana.com/0/1125859137800433/1200415335882260
1. Fixed props validation
2. Replace memo wrapping for resolving <anonymous> component

fix: NavbarButton: refactoring && fixed props validation

---

src/components/GridLayout/GridLayout.js
src/components/HFUI/HFUI.container.js
src/redux/middleware/ws/on_message.js

ASANA Ticket: [prop-types startup issue](https://app.asana.com/0/1125859137800433/1200440956264708/f)

fix: prop-types startup error

---

src/components/ExchangeInfoBar/ExchangeInfoBar.js
src/components/ExchangeInfoBar/style.scss
src/hooks/useSize.js

Context:
https://files.slack.com/files-pri/T045ARQGE-F023Y6MGW3H/image.png
Asana:
https://app.asana.com/0/1125859137800433/1200260622693080
After this PR:

(fix) Ticker font style improvement & Tickerlist scroll height fix

---

src/components/OrderForm/OrderForm.js

ASANA Ticket: [Rename Futures labeling to derivatives](https://app.asana.com/0/1125859137800433/1200447882518498/f)
UI Demo:

improvement: rename futures into derivatives

---

src/components/OrderForm/OrderForm.js
src/components/OrderForm/style.scss

ASANA Ticket: [Instead of dropdown Exchange/margin from orders form add buttons or toggle](https://app.asana.com/0/1125859137800433/1200447882518496/f)
UI Demo:

Using buttons for context switch instead of dropdown

---

src/components/OrderForm/OrderForm.js

ASANA Ticket: [UI: rebuild OrderForm fields validation with validate_params from bfx-hf-algo](https://app.asana.com/0/1125859137800433/1200038332394566/f)
https://user-images.githubusercontent.com/35810911/122424759-80488f80-cf7e-11eb-91b4-96fba7e0d5f4.mp4

improvement: bfx-hf-algo params validation

---

src/components/AlgoOrdersTable/AlgoOrdersTable.columns.js
src/components/AtomicOrdersTable/AtomicOrdersTable.columns.js
src/components/BalancesTable/BalancesTable.columns.js
src/components/PositionsTable/PositionsTable.columns.js

ASANA Ticket: [column width on table component need to be relative](https://app.asana.com/0/1125859137800433/1200383864759508/f)
https://user-images.githubusercontent.com/35810911/122758430-4fbb6b00-d288-11eb-8fb1-f92abe1dc0bb.mp4

improvement: using dynamic column width for tables

---

src/components/OrderForm/style.scss

Remove left and right spacing from .ufx-dropdown .list

---

src/components/StatusBar/StatusBar.container.js
src/components/StatusBar/StatusBar.js

ASANA Ticket: [WS Connected is always active (with no internet)](https://app.asana.com/0/1125859137800433/1200441922426818/f)
UI Demo:

fix: ws connection status

---

src/components/GridLayout/GridLayout.js
src/components/MarketSelect/MarketSelect.js
src/components/OrderForm/OrderForm.container.js
src/util/ui.js

ASANA Ticket: [OrderForm atomic orders are missing](https://app.asana.com/0/1125859137800433/1200520941341282/f)
Before:
After:

fix: OrderForm atomic orders issue

---

src/components/OrderForm/FieldComponents/ui.ticker.js
src/components/OrderForm/OrderForm.js
src/components/OrderForm/style.scss
src/orders/limit.js

https://app.asana.com/0/1125859137800433/1199637468764447/f
When user click on ticker, price input is filled with ticker's value. Tickerbar is always above buttons

improvement: OrderForm: fill price form on ticker click

---

src/components/OrderHistory/OrderHistory.js
src/ui/Panel/index.js

fix: Panel prop validation

---

src/components/Joyride/Joyride.js
src/components/Joyride/Joyride.steps.js
src/components/Joyride/index.js
src/pages/MarketData/MarketData.js
src/pages/StrategyEditor/StrategyEditor.js
src/pages/Trading/Trading.js

Before (Starts at 3 :( ):
New colors:

(fix) Fix broken trading tour and update colors

---

src/components/Navbar/Navbar.LayoutSettings.js

ASANA Ticket: [when on default layout > click on save will crash the app](https://app.asana.com/0/1125859137800433/1200530699184425/f)
https://user-images.githubusercontent.com/35810911/123657652-819c7680-d820-11eb-9f87-2597732942d2.mp4

fix: crash on layout saving

---

src/components/StrategyEditor/StrategyEditor.container.js
src/components/StrategyEditor/StrategyEditor.js
src/components/StrategyEditor/StrategyEditorPanel/StrategyEditorPanel.js
src/components/StrategyEditor/style.scss

ASANA Ticket: [fix & refactor StrategyEditor](https://app.asana.com/0/1125859137800433/1200510047655567/f)
Description:
- refactored Strategy Editor into a clear, functional component, removed unused & repeating code
- updated error message UI layout
- [Firefox] showing row & column where the error occurred before its message
- showing indicator to the Strategy Editor's Panel component while strategy is being executed
https://user-images.githubusercontent.com/35810911/123091734-385fb780-d419-11eb-9b59-6808b7975eac.mp4

refactor: Strategy Editor

---

src/redux/adapters/ws.js
src/redux/middleware/ui/index.js
src/redux/middleware/ws/on_message.js
src/redux/sagas/ws/on_connected.js
src/redux/sagas/ws/on_disconnected.js

fix: notification unique key warning

---

src/components/NotificationsSidebar/style.scss
src/components/StrategyEditor/StrategyEditorPanel/StrategyEditorPanel.js
src/ufx-customise.scss
src/ui/Panel/style.scss
src/variables.scss

(improvement) Notifications colors

---

package-lock.json
package.json
src/components/ExchangeInfoBar/ExchangeInfoBar.js
src/components/ExchangeInfoBar/ExchangeInforBar.constants.js
src/components/ExchangeInfoBar/style.scss
src/components/TradesTablePanel/style.scss
src/redux/reducers/ui/default_layout_trading.js
src/ufx-customise.scss

Improve spacings in the tickerlist:
Depends on ufx-ui PR: https://github.com/bitfinexcom/ufx-ui/pull/75

(improvement) Tickerlist UI

---

src/components/NotificationsSidebar/Notification.js
src/components/NotificationsSidebar/NotificationsSidebar.container.js
src/components/NotificationsSidebar/NotificationsSidebar.js
src/redux/actions/ui.js
src/redux/reducers/notifications/index.js

ASANA Ticket: [live notifications are not displayed](https://app.asana.com/0/1125859137800433/1200548586821534/f)

fixed: live notifications are not shown

---

src/redux/reducers/ui/index.js

ASANA Ticket: [Remove component will keep [Save] disabled](https://app.asana.com/0/1125859137800433/1200548557089364/f)
https://user-images.githubusercontent.com/35810911/124160973-5f0e9580-da8c-11eb-8c1b-97118d0f343d.mp4

fixed: remove component will not trigger save button

---

package.json

ticket - https://app.asana.com/0/1125859137800433/1200553522605421/f
https://github.com/bitfinexcom/ufx-ui/pull/85

Updated ufx-ui to 0.8.6

---

package-lock.json
package.json

ticket - https://app.asana.com/0/1125859137800433/1200553522605421/f

Updated ufx-ui to 0.8.7

---

src/components/Navbar/Navbar.LayoutSettings.js

ASANA Ticket: [Add limitation on component dropdown width](https://app.asana.com/0/1125859137800433/1200554799879125/f)
Before:
After:

improvement: layout settings truncating layout ID

---

src/redux/reducers/ui/index.js

ASANA Ticket: [Always shown new formatted layout modal bug](https://app.asana.com/0/1125859137800433/1200564658744913/f)
https://user-images.githubusercontent.com/35810911/124671758-7fcc5600-dea5-11eb-9c25-7898abae7535.mp4

fix: always shown 'new layout format' modal bug

---

src/components/GridLayout/GridLayout.js
src/components/TradesTablePanel/TradesTablePanel.js
src/redux/selectors/ui/get_market_components.js

Task: [UI: trading stage: two trades components, close one, other crashed](https://app.asana.com/0/1125859137800433/1200441083677330/f)

(fix) trades subscription issue

---

package-lock.json
package.json
src/components/OrderForm/FieldComponents/input.checkbox.js
src/constants/AtomicOrdersCheckboxHelpText.js
src/orders/fok.js
src/orders/ioc.js
src/orders/limit.js
src/orders/market.js
src/orders/stop.js
src/orders/stop_limit.js
src/orders/trailing_stop.js

https://github.com/bitfinexcom/ufx-ui/pull/82
ticket - https://app.asana.com/0/1125859137800433/1200564160940294
Now if user hovers cursor to checkbox's placeholder in atomic orders form, it is showing helping information about current option, as it works on web

improvement: OrderForm: added helping messages for checkboxes

---

src/components/Navbar/style.scss

ticket - https://app.asana.com/0/1200372033300327/1200576444678629

(fix): Logo moved out in Safari

---

public/lib/app_menu_template.js

ticket - https://app.asana.com/0/1125859137800433/1200691568353031

(feature) Removed 'Edit' in top menu

---

scripts/start-api-server.js

https://github.com/bitfinexcom/bfx-hf-ui-core/pull/25
Proxy support for api.bitfinex.com

(fix) Resolved issue for api v1 proxy

---

public/lib/app_menu_template.js

Reverts bitfinexcom/bfx-hf-ui#560

Revert "(feature) Removed 'Edit' in top menu"

---

package-lock.json
package.json
scripts/postbuild.bat

ASANA Ticket: [Make all scripts cross platform compatible](https://app.asana.com/0/1125859137800433/1200915378040105/f)
Also fixes https://github.com/bitfinexcom/bfx-hf-ui-core/issues/101 issue
- ported build scripts for windows
- fixed bug when bfx-hf-ui-core was unable to fetch & merge latest version

(fix) cross platform script compatibility

---

package-lock.json
package.json

ASANA Ticket: [FE implementation : light theme](https://app.asana.com/0/0/1201111079368770/f)
Description:
- updated bfx-hf-server (needed for https://github.com/bitfinexcom/bfx-hf-ui-core/pull/154)

(improvement) bfx-hf-server update

---

public/lib/app.js

Reverts bitfinexcom/bfx-hf-ui#626

Revert "(refactor) ignore CSP header rule for chart-iframe"

---

package-lock.json
package.json
scripts/start-api-server.js

enables scoped DMS for electron app
plus: externalize config for remote DMS

update core: scoped dms

---

package.json
scripts/start-api-server.js

more info at: https://github.com/bitfinexcom/bfx-hf-algo/pull/198

Enable signal tracer

---

scripts/start-api-server.js

Added strategy execution path as required by the latest bfx-hf-server update

(improvement) Added strategy execution path

---

README.md
package.json
public/constants.js
public/lib/app_menu_template.js
scripts/auto-updater/bfx.mac.updater.js
scripts/enforce-macos-app-location.js
scripts/start-api-server.js
scripts/start-ds-bitfinex.js

[Change app names from "Honey Framework" to "Bitfinex Honey"](https://app.asana.com/0/1201849173362898/1202435418835689/f)

(chore) replace HoneyFramework with Bitfinex Honey

---

public/lib/app_menu_template.js

[Allow devtools access for RC release](https://app.asana.com/0/1201849173362898/1202434985843144/f)
Steps to use:
1. click Diagnostics -> Toggle Developer Tools
2. click Diagnostics -> Reload (optional: without this Network/WS connections won't show up as it needs to be reconnected to monitor with devtools)

(feature) add devtools menu for RC versions

---

README.md
package-lock.json
package.json

Prepare RC

---

package.json

ticket - https://app.asana.com/0/1201848935859401/1202696553724388/f

(fix) Use properly app name on menu icon hover in linux

---

package.json
public/lib/app.js
public/lib/preload.js
public/utils/appMenu.js
public/utils/syncReadUserSettings.js

ticket - https://app.asana.com/0/1201849173362898/1202789235901910
- removed unused script, worked unexpected
- set min width and min height for application window
- toggle fullscreen from app menu, hotkey (F11) and setting modal from core
https://user-images.githubusercontent.com/81973123/186422869-c3c2ac2a-4184-4e02-b706-555f57276548.mp4

(feature) Fullscreen mode

---

public/lib/app.js
public/utils/tray.js

ticket - https://app.asana.com/0/1201849173362898/1202907567859177
https://www.electronjs.org/docs/latest/faq#my-apps-tray-disappeared-after-a-few-minutes

(fix) Resolve issue with app's tray disappeared

---

package-lock.json
public/lib/app.js
public/lib/preload.js

ticket - https://app.asana.com/0/1200372033300327/1202881975386000
related to: https://github.com/bitfinexcom/bfx-hf-ui-core/pull/531

(improvement) Ask the user for permission to update the application

---

package-lock.json
package.json
scripts/start-api-server.js

this will enable sending metrics to the server.

add metrics server url + prepare RC

---

public/lib/app.js

ticket - https://app.asana.com/0/1201849173362898/1203058185816468/1203053948212103

(fix) Added pattern for skipping updater error 

---

package-lock.json
package.json
public/lib/app.js
public/utils/appMenu.js

ticket - https://app.asana.com/0/home/1200372033295260/1203078941561027
based on #746, #745 
https://user-images.githubusercontent.com/81973123/193296895-29fa5f08-1d71-4096-a96c-14bc9f598d7d.mp4

(improvement) Save window state between sessions

---

package-lock.json
package.json
public/lib/app.js
public/lib/preload.js
public/utils/saveStrategiesToZIP.js

ticket - https://app.asana.com/0/1200372033300327/1203088836623925

(feature) Save strategies to ZIP archive

---

package-lock.json
package.json
scripts/auto-updater/bfx.mac.updater.js

ticket - https://app.asana.com/0/1201848935859401/1203332740735808
[DOCS](https://github.com/cthackers/adm-zip/wiki/ADM-ZIP#void-extractalltostring-targetpath-boolean-overwrite--false)

(refactor) Removed extract-zip library

---

public/lib/app.js

ticket - https://app.asana.com/0/1201849173362898/1204104947460943
issue - https://github.com/bitfinexcom/bfx-hf-ui/issues/807

(improvement) Accessibility for small monitors

---

public/lib/app.js

app.log
> {"message":"Initialising a WebSocket connection","level":"info","action":"local_connection_init"}
{"message":"Initialising a WebSocket connection","level":"info","action":"local_connection_init"}
{"message":"WebSocket connection was established","level":"info","action":"local_connection_success"}
{"message":"WebSocket connection was established","level":"info","action":"local_connection_success"}
{"message":"Authorised to Honey successfully","level":"info","action":"app_login_success"}
{"message":"App setting was updated","level":"info","action":"setting_update_success"}
{"message":"Atomic order closed","level":"info","action":"atomic_order_executed"}
{"message":"Setting update requested.","level":"info","action":"setting_update_requested"}
{"message":"App setting was …

(fix) Resolve issue with [object Object]

---

scripts/start-ds-bitfinex.js

ticket - https://app.asana.com/0/1201849173362898/1202373798772445
dependency - https://github.com/bitfinexcom/bfx-hf-data-server/pull/60

(feature) Add path to sqlite db

---

README.md

ticket - https://app.asana.com/0/1200372033300327/1208310626438187/f

Readme: add DMS removal notice
