bitfinexcom/bfx-hf-ui

package-lock.json
package.json
src/components/AlgoOrderDefenitionsTable/AlgoOrderDefinitionsTable.js
src/components/AlgoOrderTable/AlgoOrderTable.columns.js
src/components/AlgoOrderTable/AlgoOrderTable.container.js
src/components/AlgoOrderTable/AlgoOrderTable.js
src/components/HFUI/_HFUI.scss
src/redux/actions/algo-orders.js
src/redux/reducers/algo-orders.js

Creates a new endpoint in the `bfx-hf-server` to activate/deactive a given algo definition. This pull request updates the current redux patterns to hit that endpoint. See https://github.com/bitfinexcom/bfx-hf-server/pull/5

AlgoOrderTable: connect to new :id/state/set endpoint on hf-server

---

README.md

Instructions were missing the important step of having the user create the folder where the local db will be stored and creating the db files. Without that, it errors out when trying to run.

Missing setup step of creating db location

---

src/components/Backtester/reports/HistoricalReport.js

The test results are the most important ones, yet the chart is
taking up all space on laptps with small displays.
This changes the order of the components, so that test results are
handily available.

backtest: display test results on top

---

src/redux/middleware/ga/index.js

This anonymises the client IP so google is not tracking the IP.
This is useful for german vendors of honey framework solutions and
also in general a nice move towards better data privacy

ga: anonymise user IP

---

src/components/CreateNewStrategyModal/CreateNewStrategyModal.js

When HF UI was a real client/server application, encryption would have made sense,
but right now everything ones on the client with a hardcoded salt.
This PR removes a notice that states that we send the data encrypted to a server.

ui: remove encryption notice

---

src/components/TradingStatePanel/TradingStatePanel.js

the panel does just support strings as tab title, which are used
as render keys. when react elements are passed, the key results in
an `[Object object]` key, which repeats itself and throws a lot of
errors.

fix: same key prop for passed react element

---

src/components/TradingStatePanel/TradingStatePanel.js
src/ui/Panel/Panel.props.js
src/ui/Panel/index.js

support html in our panels now by introducing custom keys, because
we can't derive keys from passed html / react elements.
require for the positions counter.

fix: Panel element with html and keys

---

clear.sh

the regex matches one of our modules, `bfx-hf-backtest`, which was
then missing after building on the ci.

build: don't delete bfx-hf-backtest

---

scripts/start-api-server.js

depends on https://github.com/bitfinexcom/bfx-hf-server/pull/47 (already merged)

start-api-server: make api urls configurable

---

src/components/Backtester/forms/HistoricalForm.js

after receiving user feedback, this provides a better user
experience for users that select high volume pairs and test for
the first time, as result creation time  with just candles is
linear and not in relation to the trade volume.

backtesting: just preselect trades

---

.eslintrc.json
package-lock.json
package.json
src/ui/Dropdown/Dropdown.js

this PR upgrades `eslint-plugin-import` and fixes two eslint errors:
one rule was disabled in 833920a - which is reverted in this PR
the other was still persisting for `npm run lint -- --fix`
both issues are fixed by @AntonNazarenko's commit

fix eslint errors, upgrade eslint-plugin-import

---

src/redux/reducers/ui/index.js

issue: 'exec.str' message was sent without strategy content. 
This PR making the app to include strategy content to the WS message

fix:strategy content now stores in "content" field

---

src/components/LiveStrategyExecutor/LiveStrategyExecutor.container.js

Fix for next issue: 
When Strategy Editor / Execute is selected with no strategy, opening strategy will not update page

FIX: update exec strategy page after strategy select

---

.gitignore
public/constants.js
public/electron.js
public/lib/app_menu_template.js

Currently the 'Open Logs Folder' entry in the electron `app_menu_template.js` points to the wrong location, as it has moved to `os.tmpdir()` some time ago.
This extracts those constants and fixes the path, also adding two entries for the API & DS server log files themselves.Currently the 'Open Logs Folder' entry in the electron `app_menu_template.js` points to the wrong location, as it has moved to `os.tmpdir()` some time ago.
This extracts those constants and fixes the path, also adding two entries for the API & DS server log files themselves.

Fix: Expand/fix diagnostics app menu entry

---

src/components/OrderForm/OrderForm.helpers.js

given in a ui component def the default value is set to `0`, the
previous implementation was discarding it.
this PR renders 0 default values. example is the `Cancel Delay` in
`Order creates OCO`

orderforms: allow 0 as default

---

src/pages/Authentication/Authentication.container.js
src/pages/Authentication/style.scss

made app delete everything from localstorage after reset
updated save credentials button styles

clear storage after reset; fix button width

---

src/components/OrderForm/OrderForm.helpers.js

Task: [Trading Terminal: show base and quote currency in the order form]
(https://app.asana.com/0/1125859137800433/1199637468764447/f)
Sub-task: [Show base, quote currency for Price, Amount labels](https://app.asana.com/0/0/1200044397612902/f)
Before:
After:

(fix) orderform: show base and quote currency

---

src/pages/MarketData/MarketData.container.js
src/pages/StrategyEditor/StrategyEditor.container.js
src/pages/Trading/Trading.container.js
src/pages/Trading/Trading.js
src/redux/reducers/ui/index.js
src/redux/selectors/ui/get_guide_status_for_page.js
src/redux/selectors/ui/index.js

Full description: https://app.asana.com/0/1125859137800433/1200010701660159/f
Fixed guide tour on the Trading Page
Refactored code 
Added dedicated selectors

Fix: Tour not visible on Trading terminal 

---

src/pages/StrategyEditor/StrategyEditor.js

-  Hidden `Execute` tab in Strategy Editor until the feature will be fully implemented

Hide strategy editor execute tab

---

src/index.scss

Bug fix for calendar overlapping button
Task: [UI: Backtesting: "Use Candles" and "Use Trades" Checks Remain Active While Selecting Date](https://app.asana.com/0/1125859137800433/1199182620003269/f)
Before:
After:

fix: button overlay on the calendar

---

src/components/PositionsTable/PositionsTable.columns.js

Task: [Align positions table colors with web-app](https://app.asana.com/0/1125859137800433/1198968550128741/f)
Before:
After:

Added highlighting for P/L & P/L % cols

---

src/components/OrderForm/OrderForm.helpers.js
src/orders/bitfinex/fok.js
src/orders/bitfinex/ioc.js
src/orders/bitfinex/market.js
src/orders/bitfinex/stop.js
src/orders/bitfinex/stop_limit.js
src/orders/bitfinex/trailing_stop.js

ASANA Ticket: [UI: Remove Reduce only checkbox from Exchange orders](https://app.asana.com/0/1125859137800433/1200016200363070/f)
Before:
After:

Fixed 'reduce only' field being displayed for exchange trading

---

public/electron.js
public/lib/app.js

previously, on OSX child processes stayed open, now `SIGKILL` is
sent and the background services exit properly.
additionally on darwin the app is completely stopped, as a
hybernate process does not make sense for the app.

fix: close all background services

---

src/components/NotificationsSidebar/Notification.js
src/components/StrategyEditor/StrategyEditor.container.js
src/components/StrategyEditor/StrategyEditor.js
src/pages/StrategyEditor/StrategyEditor.js

Description:
strategy editor: remember selected strategy after page change
steps:
1. On strategy editor, select strategy, run backtest
2. visit trading terminal/market data page
3. now it shows previously selected strategy, and clicking 'start' on backtest tab will run strategy successfully
https://user-images.githubusercontent.com/29878604/114008204-a1567b00-987f-11eb-8641-bd48d824e572.mov

(improvement) strategy editor: remember selected strategy after page change

---

src/orders/bitfinex/limit.js

ASANA Ticket: [[Margin Trading]: Reduce only flag is missing on margin limit orders](https://app.asana.com/0/1125859137800433/1200136010718941/f)
UI Demo:

Added reduce-only into limit order

---

src/components/OrderForm/style.scss
src/ui/Dropdown/style.scss

ASANA Ticket: [UI: TWAP: Dropdown icon overlaps with settings for "Price Condition" on a custom "Price Target"](https://app.asana.com/0/1125859137800433/1199921049101626/f)

Fixed dropdown TWAP overlap

---

src/components/OrderForm/style.scss

ASANA Ticket: [Trading Terminal: leverage slider not aligned](https://app.asana.com/0/1125859137800433/1200157146284912/f)
Before:
After:

fix: input range shift

---

src/components/ActiveAlgoOrdersModal/style.scss

Fix for ActiveAlgoOrdersModal's broken layout.
* the issue is reproducible on Firefox.
Before:
After:

fix: broken algo modal layout

---

public/lib/app.js
src/components/NavbarButton/NavbarButton.js

Ticket: https://app.asana.com/0/0/1200101612219001/1200196533316186/f
Description: From now on any external link with the `target="_blank"` will be opened in the default browser instead of the Electron application.
Before:
https://www.loom.com/share/f54f9ec9eaae4263af09a73a11c68695
After:

fix: opening external link in the default browser

---

src/pages/Settings/Settings.container.js
src/pages/Settings/Settings.js

Description:
- fix for the "Bitfinex error: auth: dup" issue when submitting new API keys.
- removed unused code in the Settings & Settings.container components.
- removed obsolete exID param from 'api_credentials.save'
UI Demonstation:

fix: 'Bitfinex error: auth: dup' when submitting new API keys

---

src/components/OrderForm/OrderForm.container.js

Related to #353.
Fixed the modal form to send the API keys in the same format as Settings form does.

fix: OrderForm API keys modal - sending API keys in the new format

---

src/components/OrderForm/Modals/SubmitAPIKeysModal/SubmitAPIKeysModal.js
src/components/OrderForm/Modals/SubmitAPIKeysModal/SubmitAPIKeysModal.props.js
src/components/OrderForm/Modals/UnconfiguredModal/UnconfiguredModal.js
src/components/OrderForm/Modals/UnconfiguredModal/UnconfiguredModal.props.js
src/components/OrderForm/OrderForm.container.js
src/components/OrderForm/OrderForm.js
src/components/OrderForm/style.scss

ASANA Ticket: [When inside HF on paper trading specify that users need to enter paper trading keys](https://app.asana.com/0/1125859137800433/1200101612218997/f)
Note: you have to run `npm run build-css` after you've pulled these changes.

Notifying users to enter Paper Trading keys

---

package-lock.json
package.json
src/index.scss
src/ufx-customise.scss

**Depends on**
https://github.com/bitfinexcom/ufx-ui/pull/18
**Description:**
- updated ufx to 0.2.2 which solves incorrect cjs/esm builds while working on windows
- remove node_modules/node-sass-tilde-importer (as it incorrectly puts absolute path for ufx-ui.scss content while building on windows system)
- remove ~ syntax since we now removed node_modules/node-sass-tilde-importer parser
- pass --include-path ./node_modules to node-sass to support "normalize.css/..." instead of "~normalize.css/..."

(fix) fix ufx ref error and '~' syntax error while building on windows

---

src/ui/Modal/Modal.js

- [Resume algo trade dialog should not be closed by clicking outside of dialog ](https://app.asana.com/0/1125859137800433/1200222037480528)
-  Prevented AOs modal from closing on overlay clicking
https://user-images.githubusercontent.com/41899906/116435535-236d0a80-a854-11eb-8f2f-f0530c8e8d9a.mov

Prevent AOs modal close on overlay click

---

src/redux/sagas/ui/worker_fetch_remote_version.js

ASANA Ticlet: [Fix incorrect version retrieval bug](https://app.asana.com/0/1125859137800433/1200296600486401/f)
Description: Currently the redux worker retrieves the data from `package.json` (as a string) and tries to get the `version` value from it, which will always return undefined.
This PR fixes this bug (by parsing JSON from the returned string) and uses a dedicated API endpoint for getting version information (instead of requesting much bigger `package.json`).
UI Demo:

fix: version retrieval bug

---

src/components/HFUI/HFUI.js

- [UI: fix HFUI props warnings ](https://app.asana.com/0/1125859137800433/1200302286246223)
-  Added default props to fix these warnings on the initial app rendering:

Fix: HFUI props warnings

---

src/ufx-customise.scss

(fix) Change dropdown active item color

---

src/pages/Authentication/style.scss
src/ui/Input/style.scss

- Fixed input password icon alignment on the login page
- Task: https://app.asana.com/0/1125859137800433/1200332623388391

Fix: input password icon alignment

---

src/components/HFUI/HFUI.container.js
src/components/HFUI/HFUI.js
src/redux/actions/ws.js

ASANA Ticket: [UI: app exit - send pause event to server](https://app.asana.com/0/1125859137800433/1200341518248846/f)
The `unloadHandler` listens to `beforeunload` event and triggers `onUnload` method before the app is closed.

fix: send pause event to server

---

src/components/Backtester/forms/HistoricalForm.js
src/components/OrderForm/FieldComponents/input.date.js

Resolved issue with initial startDate value in HistoricalForm component. Children component requires Date format value but taken number format (timestamp) value

fixed: HistoricalForm: changed startDate initial format

---

src/redux/sagas/ws/index.js
src/redux/sagas/ws/worker_ping_connection.js

ASANA Ticket: [Reconnect modal false positive](https://app.asana.com/0/1125859137800433/1200377606276626/f)
Description: Bitfinex Websocket public API does require pinging it regularly if there are no other messages being sent, otherwise the connection will be dropped which causes a false positive 'Reconnect Modal'.
This pull request adds a worker, which will ping a websocket connections every 30 seconds except those which do not require it (API and data servers).

fix: false positive on reconnect modal

---

src/components/OrderHistory/OrderHistory.container.js
src/components/OrderHistory/OrderHistory.js
src/components/OrderHistory/index.js
src/pages/MarketData/MarketData.container.js

ASANA Ticket: [Order history table when no elements should have bigger fonts and headers removed task](https://app.asana.com/0/1125859137800433/1200383864348742/f)
Description:
- improved empty message in order history
- refactored components, added prop validation
- moved redux logic into separated container
- fixed MarketData unused variables warning
UI Demo:

improvement: OrderHistory empty message

---

src/pages/Authentication/style.scss

ticket - https://app.asana.com/0/1125859137800433/1200391973294454
- changed input container style property z-index from 999999 to 1

fix: Authorization: overlaping notifications

---

src/components/BalancesTable/BalancesTable.js
src/util/ui.js

ASANA Ticket: [Add message for no balance (and remove column header)](https://app.asana.com/0/1125859137800433/1200426227532519/f)
Description:
- added message to be shown in case if balances table is empty.
- added method to localise numbers (add semicolons in them).
UI Demo:

improvement: empty balance message; table prices localisation

---

src/components/Layout/style.scss
src/components/OrderForm/OrderForm.js
src/components/OrderForm/style.scss

ASANA Ticket: [Execute orders will be visible under set API keys](https://app.asana.com/0/1125859137800433/1200421887481897/f)
UI Demo:

fix: orderform always visible execute orders

---

src/components/AtomicOrdersTable/AtomicOrdersTable.columns.js
src/components/AtomicOrdersTable/AtomicOrdersTable.js
src/components/AtomicOrdersTable/style.scss
src/components/OrderHistory/OrderHistory.js
src/hooks/useSize.js
src/index.scss
src/ui/Panel/index.js

ASANA Ticket: [Add bars instead of circles on orders and order history for shorter width](https://app.asana.com/0/1125859137800433/1200426041616722/f)
Description: In this PR I used Jason's [useSize hook](https://github.com/bitfinexcom/bfx-hf-ui/pull/477) to implement switching from circles into bars and vice versa on OrderHistory and AtomicOrders table based on component width.
https://user-images.githubusercontent.com/35810911/122222321-acdaa980-cea1-11eb-8811-2ef1793e57f6.mp4

improvement: table bar/circle markers based on component's width

---

src/components/OrderForm/OrderForm.js

ASANA Ticket: [OrderForm data should be processed before trying to validate it](https://app.asana.com/0/1125859137800433/1200516437683803/f)
Description: `validateParams` method expects to receive data processed via the `processParams` method, otherwise it will cause false positive errors when trying to submit some algo orders (Accumulate/Distribute, for example).

fix: process data before it's validation

---

src/components/ChartPanel/ChartPanel.js
src/components/ExchangeInfoBar/style.scss
src/redux/reducers/ui/index.js

Fixes issue reported by Robert https://bitfinex.slack.com/archives/CKKLH6HA9/p1624538940331100
There's a format change in the layouts, this PR will transform the old format to the new. It will keep the old default layouts saved under the old key (without " Layout" suffix) as they may have been changed by the user.

(fix) Saved layout compatibility

---

config/webpack.config.js

This fixes @ufx-ui Provider errors when using npm link.
Reference:
https://github.com/reduxjs/react-redux/issues/1489

(fix) Redux provider error for linked packages

---

src/components/OrderForm/OrderForm.js

Description: `onFieldChange` had a condition where it checked whether the field entered was disabled.
It was useless for 2 reasons:
- the disabled state is already verified in the inputs themselves via `verifyConditionsMet` helper
- `onFieldChange` treated `disabled` param as `boolean`, not as `object` so it always returned `true` when the `disabled` param was present in `field` object
UI Demo:

fix: OrderForm not working input

---

src/components/OrderForm/Modals/UnconfiguredModal/UnconfiguredModal.js
src/components/OrderForm/style.scss

This makes it match more with the rest of the theme.
Before:
After:

(improvement) UI of submit api keys

---

src/components/CreateNewStrategyModal/CreateNewStrategyModal.js
src/components/StrategyEditor/StrategyEditorPanel/StrategyEditorPanel.js
src/index.scss

ASANA Ticket: [Add Limitation to Strategy editor name](https://app.asana.com/0/1125859137800433/1200554799879129/f)
Description:
- Added limitation for maximum label length (150 chars).
- Added Tooltip for labels which are too long to display.
https://user-images.githubusercontent.com/35810911/124463327-42bb7300-dd82-11eb-9d85-d4784e551001.mp4

improvement: Strategy Editor label limitation

---

src/util/ui.js

ticket - https://app.asana.com/0/1200372033300327/1200534517432943
Changed localiseNumber fn, because Safari doesn't support lookbehind regexp (https://caniuse.com/js-regexp-lookbehind)

(fix) LocaliseNumber: compatibility with safari

---

src/util/ui.js

ASANA Ticket: [localiseNumber crashing when no input provided](https://app.asana.com/0/1125859137800433/1200580394882108/f)
Description: When opening Order Form order before HF Connected status becomes green, the app will crash because no input (bid/ask number) is provided to the `localiseNumber` function.
Now the default input is 'N/A':

fix: localiseNumber crashing when no input provided

---

src/components/RemoveExistingStrategyModal/RemoveExistingStrategyModal.js
src/components/RemoveExistingStrategyModal/style.scss

ASANA Ticket: [Remove strategy overlapping when the names are too long](https://app.asana.com/0/1125859137800433/1200609319761299/f)

fix: remove strategy modal for long stategy names

---

src/components/Navbar/Navbar.LayoutSettings.js
src/components/OpenExistingStrategyModal/OpenExistingStrategyModal.js
src/components/StrategyEditor/StrategyEditorPanel/StrategyEditorPanel.js
src/ui/Panel/index.js
src/util/ui.js

ticket  - https://app.asana.com/0/1200372033300327/1200582533101487
Avoiding duplication of logic

(feature) StrategyEditor: showing '...' for long strategy names in open strategy modal

---

clear.sh

As reported by #574, clear.sh script produces some warnings while running.
Before:
After:

(fix) clear.sh warnings

---

public/lib/app.js

[electron: load chart frame from hchart.bitfinex.com](https://app.asana.com/0/1125859137800433/1201435300092016/f)
Depends: [(refactor) electron: update chart_url](https://github.com/bitfinexcom/bfx-hf-ui-core/pull/193)

(refactor) ignore CSP header rule for chart-iframe

---

public/lib/app.js
public/utils/appMenu.js

ticket - https://app.asana.com/0/1200372033300327/1203004971858308
Using the keyboard shortcut `Cmd+F11` for fullscreen toggle on MacOS, because `F11` is a system shortcut.
branched from https://github.com/bitfinexcom/bfx-hf-ui/pull/745

(fix) MacOS fullscreen

---

public/constants.js
public/lib/app.js
public/utils/appMenu.js

ticket - https://app.asana.com/0/1201849173362898/1203140058772292
Added Pendo Visual Studio button in Diagnostic menu
Using [setWindowOpenHandler](https://www.electronjs.org/ru/docs/latest/api/web-contents#contentssetwindowopenhandlerhandler) instead of [deprecated](https://www.electronjs.org/ru/docs/latest/breaking-changes#removed-webcontents-new-window-event) `new-window` event handler
https://user-images.githubusercontent.com/81973123/212473219-380ab146-62f4-41ba-86b3-9e6646d604ed.mp4

(fix) Pendo Visual Design Studio

---

.env
.env.example
.gitignore
package.json

ASANA Ticket: [Cleanup Move env vars out of build/start script](https://app.asana.com/0/1201848935859401/1203020791627955/f)
(the app is running based on the vars set in the .env file of the bfx-hf-ui repo)

(improvement) Using .env instead of setting variables in the package.json

---

package-lock.json
package.json
scripts/auto-updater/bfx.mac.updater.js

ticket - https://app.asana.com/0/1201849173362898/1205172768485798
reverted https://github.com/bitfinexcom/bfx-hf-ui/commit/6be6d62667b78e5ee7631f2c43366c48fccf9357

(fix) Autoupdate on MacOS
